
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned long u32;
typedef signed char s8;
typedef short s16;
typedef long s32;
typedef float f32;
typedef enum AssetLevelObjectTranslationTableEnum
{
  ASSET_OBJECT_ID_DOME,
  ASSET_OBJECT_ID_KREMCAR,
  ASSET_OBJECT_ID_BADGERCAR,
  ASSET_OBJECT_ID_TORTCAR,
  ASSET_OBJECT_ID_CONKACAR,
  ASSET_OBJECT_ID_SMARTIETREE,
  ASSET_OBJECT_ID_FRONTTYRE,
  ASSET_OBJECT_ID_BACKTYRE,
  ASSET_OBJECT_ID_HITTESTER,
  ASSET_OBJECT_ID_WORLDGATE,
  ASSET_OBJECT_ID_MIDIFADE,
  ASSET_OBJECT_ID_PARKWARDEN,
  ASSET_OBJECT_ID_WARDENSMOKE,
  ASSET_OBJECT_ID_ANIMATOR,
  ASSET_OBJECT_ID_BOMB,
  ASSET_OBJECT_ID_FLOWERS,
  ASSET_OBJECT_ID_SMOKE,
  ASSET_OBJECT_ID_EXIT,
  ASSET_OBJECT_ID_CAMERA_CONTROL,
  ASSET_OBJECT_ID_WORLDKEY,
  ASSET_OBJECT_ID_SETUPPOINT,
  ASSET_OBJECT_ID_AUDIO,
  ASSET_OBJECT_ID_AUDIOLINE,
  ASSET_OBJECT_ID_DINOSAUR1,
  ASSET_OBJECT_ID_CHECKPOINT,
  ASSET_OBJECT_ID_LEVELDOOR,
  ASSET_OBJECT_ID_FOGCHANGER,
  ASSET_OBJECT_ID_AINODE,
  ASSET_OBJECT_ID_WEAPONBALLOON,
  ASSET_OBJECT_ID_MISSILE,
  ASSET_OBJECT_ID_DOME1,
  ASSET_OBJECT_ID_SNOWMEN,
  ASSET_OBJECT_ID_DOME2,
  ASSET_OBJECT_ID_SIGNS,
  ASSET_OBJECT_ID_REEDS,
  ASSET_OBJECT_ID_BEACHTREE,
  ASSET_OBJECT_ID_AUDIOSEQLINE,
  ASSET_OBJECT_ID_AUDIOSEQ,
  ASSET_OBJECT_ID_STOPWATCHICON,
  ASSET_OBJECT_ID_EFFECTBOX,
  ASSET_OBJECT_ID_COINCREATOR,
  ASSET_OBJECT_ID_TREASURESUCKER,
  ASSET_OBJECT_ID_BRIDGE,
  ASSET_OBJECT_ID_LAVASPURT,
  ASSET_OBJECT_ID_BOMBEXPLOSION,
  ASSET_OBJECT_ID_WBALLOONPOP,
  ASSET_OBJECT_ID_BUBBLEWEAPON,
  ASSET_OBJECT_ID_DOME5,
  ASSET_OBJECT_ID_DINOISLE,
  ASSET_OBJECT_ID_AUDIOREVERB,
  ASSET_OBJECT_ID_POSARROW,
  ASSET_OBJECT_ID_WINDSAIL,
  ASSET_OBJECT_ID_COLLECTEGG,
  ASSET_OBJECT_ID_SKYCONTROL,
  ASSET_OBJECT_ID_STOPWATCHHAND,
  ASSET_OBJECT_ID_KREMLINHOVER,
  ASSET_OBJECT_ID_BADGERHOVER,
  ASSET_OBJECT_ID_TORTHOVER,
  ASSET_OBJECT_ID_CONKAHOVER,
  ASSET_OBJECT_ID_DOME3,
  ASSET_OBJECT_ID_GLOVE,
  ASSET_OBJECT_ID_FLAMINGTORCH,
  ASSET_OBJECT_ID_MIST,
  ASSET_OBJECT_ID_DOME4,
  ASSET_OBJECT_ID_TEXSCROLL,
  ASSET_OBJECT_ID_FAN,
  ASSET_OBJECT_ID_KREMPLANE,
  ASSET_OBJECT_ID_BADGERPLANE,
  ASSET_OBJECT_ID_TORTPLANE,
  ASSET_OBJECT_ID_CONKA,
  ASSET_OBJECT_ID_LOG,
  ASSET_OBJECT_ID_MODECHANGE,
  ASSET_OBJECT_ID_JETENGINE,
  ASSET_OBJECT_ID_BLUEBERRYBUSH,
  ASSET_OBJECT_ID_RUBBERSNOWTREE,
  ASSET_OBJECT_ID_SKINNYSNOWTREE,
  ASSET_OBJECT_ID_XMASTREE,
  ASSET_OBJECT_ID_ALPINESNOWTREE,
  ASSET_OBJECT_ID_RUBBERTREE,
  ASSET_OBJECT_ID_BOULDER,
  ASSET_OBJECT_ID_STOPWATCHMAN,
  ASSET_OBJECT_ID_TIGERCAR,
  ASSET_OBJECT_ID_TROPHYCAB,
  ASSET_OBJECT_ID_COIN,
  ASSET_OBJECT_ID_BANJOCAR,
  ASSET_OBJECT_ID_CHICKENCAR,
  ASSET_OBJECT_ID_MOUSECAR,
  ASSET_OBJECT_ID_TIGERHOVER,
  ASSET_OBJECT_ID_BANJOHOVER,
  ASSET_OBJECT_ID_CHICKENHOVER,
  ASSET_OBJECT_ID_MOUSEHOVER,
  ASSET_OBJECT_ID_TIGPLANE,
  ASSET_OBJECT_ID_BANJOPLANE,
  ASSET_OBJECT_ID_CHICKENPLANE,
  ASSET_OBJECT_ID_MOUSEPLANE,
  ASSET_OBJECT_ID_EGGCREATOR,
  ASSET_OBJECT_ID_CHARACTERFLAG,
  ASSET_OBJECT_ID_FLYCOIN,
  ASSET_OBJECT_ID_GOLDENBALLOON,
  ASSET_OBJECT_ID_DOME6,
  ASSET_OBJECT_ID_DOME10,
  ASSET_OBJECT_ID_PALMTREETOP,
  ASSET_OBJECT_ID_WHALE,
  ASSET_OBJECT_ID_DINOSAUR2,
  ASSET_OBJECT_ID_DINOSAUR3,
  ASSET_OBJECT_ID_RGBALIGHT,
  ASSET_OBJECT_ID_PALMPLANT,
  ASSET_OBJECT_ID_SNOWBALL,
  ASSET_OBJECT_ID_BUOY,
  ASSET_OBJECT_ID_SILVERCOIN,
  ASSET_OBJECT_ID_WEATHER,
  ASSET_OBJECT_ID_AIRZIPPERS,
  ASSET_OBJECT_ID_FIRTREE,
  ASSET_OBJECT_ID_RAMPWHALE,
  ASSET_OBJECT_ID_RAMPSWITCH,
  ASSET_OBJECT_ID_SEAMONSTER,
  ASSET_OBJECT_ID_BONUSGEM,
  ASSET_OBJECT_ID_BONUS,
  ASSET_OBJECT_ID_DOME7,
  ASSET_OBJECT_ID_INTROCAM,
  ASSET_OBJECT_ID_MAGICCARPET,
  ASSET_OBJECT_ID_LENSFLARE,
  ASSET_OBJECT_ID_LENSFLARESWITCH,
  ASSET_OBJECT_ID_HAYSTACK,
  ASSET_OBJECT_ID_PILLAR,
  ASSET_OBJECT_ID_BOULDERANIM,
  ASSET_OBJECT_ID_BOOST,
  ASSET_OBJECT_ID_MONORAIL,
  ASSET_OBJECT_ID_TROPHY,
  ASSET_OBJECT_ID_GOLDTROPHY,
  ASSET_OBJECT_ID_OILSLICK,
  ASSET_OBJECT_ID_PIGHEADCOLOURS,
  ASSET_OBJECT_ID_DOME11,
  ASSET_OBJECT_ID_RARELOGO,
  ASSET_OBJECT_ID_CHECKARROW,
  ASSET_OBJECT_ID_BIGBOSSDOOR,
  ASSET_OBJECT_ID_FIREBALLATTRACT,
  ASSET_OBJECT_ID_FIREBALL,
  ASSET_OBJECT_ID_SNOWBALLBOSS,
  ASSET_OBJECT_ID_FROG,
  ASSET_OBJECT_ID_TICKTROPHY,
  ASSET_OBJECT_ID_SHIELD,
  ASSET_OBJECT_ID_SELECTIONSHADOW,
  ASSET_OBJECT_ID_BUBBLER,
  ASSET_OBJECT_ID_PLANETYRE,
  ASSET_OBJECT_ID_DOME8,
  ASSET_OBJECT_ID_PALMTREETOPCHEA,
  ASSET_OBJECT_ID_DOME9,
  ASSET_OBJECT_ID_ANIMATION,
  ASSET_OBJECT_ID_TIGERANIMPLANE,
  ASSET_OBJECT_ID_BADGERANIMWALK,
  ASSET_OBJECT_ID_ANIMCAMERA,
  ASSET_OBJECT_ID_TIMBERDANCER,
  ASSET_OBJECT_ID_PIPSYDANCER,
  ASSET_OBJECT_ID_EMPTYHOVER,
  ASSET_OBJECT_ID_ANIMDOME,
  ASSET_OBJECT_ID_TIMBERANIMCAR,
  ASSET_OBJECT_ID_NOENTRYDOOR,
  ASSET_OBJECT_ID_N64LOGO,
  ASSET_OBJECT_ID_WIZGHOSTS,
  ASSET_OBJECT_ID_KREMSELECT,
  ASSET_OBJECT_ID_BADGERSELECT,
  ASSET_OBJECT_ID_TORTSELECT,
  ASSET_OBJECT_ID_TIGERSELECT,
  ASSET_OBJECT_ID_BANJOSELECT,
  ASSET_OBJECT_ID_CHICKSELECT,
  ASSET_OBJECT_ID_MOUSESELECT,
  ASSET_OBJECT_ID_LEEFAN,
  ASSET_OBJECT_ID_GBPARKWARDEN,
  ASSET_OBJECT_ID_GOLDBALOONSPRIT,
  ASSET_OBJECT_ID_LIGHTHOUSE,
  ASSET_OBJECT_ID_SELECTIONHILL,
  ASSET_OBJECT_ID_WIDESCREEN,
  ASSET_OBJECT_ID_OVERRIDEPOS,
  ASSET_OBJECT_ID_ANIMCAR,
  ASSET_OBJECT_ID_TRIGGER,
  ASSET_OBJECT_ID_BOLTGLOW,
  ASSET_OBJECT_ID_POSTFORPARTY,
  ASSET_OBJECT_ID_SPARKLYTHING,
  ASSET_OBJECT_ID_ANIMDINOSAUR2,
  ASSET_OBJECT_ID_TIMERANIMHOVER,
  ASSET_OBJECT_ID_ANIMBADGERPLANE,
  ASSET_OBJECT_ID_ANIMDINOSAUR1,
  ASSET_OBJECT_ID_ANIMMOUSECAR,
  ASSET_OBJECT_ID_ANIMTORT,
  ASSET_OBJECT_ID_CHICKENANIMPLAN,
  ASSET_OBJECT_ID_EMPTYHOVERANIM,
  ASSET_OBJECT_ID_RANGETRIGGER,
  ASSET_OBJECT_ID_KREMANIM,
  ASSET_OBJECT_ID_MOUSEHOVERANIM,
  ASSET_OBJECT_ID_TORTRUNNER,
  ASSET_OBJECT_ID_ANIMBANJOPLANE,
  ASSET_OBJECT_ID_CONKSELECT,
  ASSET_OBJECT_ID_LASERGUN,
  ASSET_OBJECT_ID_CONKAANIMCAR,
  ASSET_OBJECT_ID_WAVEGENERATOR,
  ASSET_OBJECT_ID_WAVEPOWER,
  ASSET_OBJECT_ID_BUTTERFLY,
  ASSET_OBJECT_ID_LASERBOLT,
  ASSET_OBJECT_ID_FISH,
  ASSET_OBJECT_ID_ANIMGENIE,
  ASSET_OBJECT_ID_SPACESHIP1,
  ASSET_OBJECT_ID_SPACESHIP2,
  ASSET_OBJECT_ID_POLYGOLDBALOON,
  ASSET_OBJECT_ID_GROUNDZIPPER,
  ASSET_OBJECT_ID_ASTEROID,
  ASSET_OBJECT_ID_PIRATESHIP,
  ASSET_OBJECT_ID_BRIGHTSTAR,
  ASSET_OBJECT_ID_WATERZIPPERS,
  ASSET_OBJECT_ID_SPACESHIP3,
  ASSET_OBJECT_ID_DOME12,
  ASSET_OBJECT_ID_CHALDOOR,
  ASSET_OBJECT_ID_STILLFROG,
  ASSET_OBJECT_ID_PARKTROPHY,
  ASSET_OBJECT_ID_BUTTERFLYBAIT,
  ASSET_OBJECT_ID_BOSSDOOR,
  ASSET_OBJECT_ID_PWSAFETELEPOINT,
  ASSET_OBJECT_ID_TRICKYTOPS,
  ASSET_OBJECT_ID_FLYINGCARPET,
  ASSET_OBJECT_ID_DOME14,
  ASSET_OBJECT_ID_PIGBOSS,
  ASSET_OBJECT_ID_DOME13,
  ASSET_OBJECT_ID_DOME15,
  ASSET_OBJECT_ID_WALRUS,
  ASSET_OBJECT_ID_DRAGONBOSS,
  ASSET_OBJECT_ID_LAMPPOST,
  ASSET_OBJECT_ID_SPACETREE,
  ASSET_OBJECT_ID_MAGICRING,
  ASSET_OBJECT_ID_HEADFORPOINT,
  ASSET_OBJECT_ID_HOMING,
  ASSET_OBJECT_ID_SPACECOLUMN2,
  ASSET_OBJECT_ID_SPACECOLUMN3,
  ASSET_OBJECT_ID_OCTOPUS,
  ASSET_OBJECT_ID_PIGFACEANIMATOR,
  ASSET_OBJECT_ID_PTERODACTYL,
  ASSET_OBJECT_ID_SMOKECLOUD,
  ASSET_OBJECT_ID_DOME16,
  ASSET_OBJECT_ID_SWCAR,
  ASSET_OBJECT_ID_AMULETPIECE1,
  ASSET_OBJECT_ID_AMULETPIECE2,
  ASSET_OBJECT_ID_AMULETPIECE3,
  ASSET_OBJECT_ID_AMULETPIECE4,
  ASSET_OBJECT_ID_STOPWATCHSELECT,
  ASSET_OBJECT_ID_TICKTOCKHOVER,
  ASSET_OBJECT_ID_TICKTOCKPLANE,
  ASSET_OBJECT_ID_SWAMULET1,
  ASSET_OBJECT_ID_SWAMULET2,
  ASSET_OBJECT_ID_SWAMULET3,
  ASSET_OBJECT_ID_SWAMULET4,
  ASSET_OBJECT_ID_ANIMKEY,
  ASSET_OBJECT_ID_TELEPORT,
  ASSET_OBJECT_ID_DIDDYSELECT,
  ASSET_OBJECT_ID_ROCKETSIGNPOST,
  ASSET_OBJECT_ID_DIDDYHOVER,
  ASSET_OBJECT_ID_LIGHTHOUSE1,
  ASSET_OBJECT_ID_DIDDYCAR,
  ASSET_OBJECT_ID_ANIMGENIE2,
  ASSET_OBJECT_ID_DIDDYPLANE,
  ASSET_OBJECT_ID_BANJODANCER,
  ASSET_OBJECT_ID_SPACECOLUMN1,
  ASSET_OBJECT_ID_MISSILEGLOW,
  ASSET_OBJECT_ID_TERRYBOSS,
  ASSET_OBJECT_ID_HOMINGGLOW,
  ASSET_OBJECT_ID_TICKTOCKDANCER,
  ASSET_OBJECT_ID_CONKADANCER,
  ASSET_OBJECT_ID_GOLDCOIN,
  ASSET_OBJECT_ID_TTDOOR,
  ASSET_OBJECT_ID_MIDIFADEPOINT,
  ASSET_OBJECT_ID_WIZPIGSHIP,
  ASSET_OBJECT_ID_TRICKYANIM,
  ASSET_OBJECT_ID_DOOROPENER,
  ASSET_OBJECT_ID_MINISHIP,
  ASSET_OBJECT_ID_OCTOBUBBLE,
  ASSET_OBJECT_ID_DOME17,
  ASSET_OBJECT_ID_DRAGONANIM,
  ASSET_OBJECT_ID_ANIMOCTO,
  ASSET_OBJECT_ID_PIGBOSS2,
  ASSET_OBJECT_ID_WIZPIG,
  ASSET_OBJECT_ID_WALRUS_ANIM,
  ASSET_OBJECT_ID_PIGLOG,
  ASSET_OBJECT_ID_WIZPIGROCKET,
  ASSET_OBJECT_ID_KEITHPIGDOOR,
  ASSET_OBJECT_ID_LIGHTNING,
  ASSET_OBJECT_ID_MAGNETFX,
  ASSET_OBJECT_ID_PIGROCKETEER,
  ASSET_OBJECT_ID_PARTICLES2,
  ASSET_OBJECT_ID_PIGBOULDER,
  ASSET_OBJECT_ID_PIGBOULDER2,
  ASSET_OBJECT_ID_PIGBOULDER3,
  ASSET_OBJECT_ID_PIGBOULDER4,
  ASSET_OBJECT_ID_PIGBOULDER5,
  ASSET_OBJECT_ID_BIGPLANET,
  ASSET_OBJECT_ID_ROCKETBIT1,
  ASSET_OBJECT_ID_ROCKETBIT2,
  ASSET_OBJECT_ID_LEVELNAME,
  ASSET_OBJECT_ID_TRICKYANIM2,
  ASSET_OBJECT_ID_TRICKYANIM3,
  ASSET_OBJECT_ID_GENIEHEAD,
  ASSET_OBJECT_ID_OCTOBOMB,
  ASSET_OBJECT_ID_MIDICHSET,
  ASSET_OBJECT_ID_ANIMGENIE3,
  NULL_OBJECT_301_ID,
  ASSET_OBJECT_ID_LIGHTHOUSE2,
  ASSET_OBJECT_ID_CHICKENCHARACTE,
  ASSET_OBJECT_ID_INFOPOINT,
  ASSET_LEVEL_OBJECT_TRANSLATION_TABLE_COUNT
} AssetLevelObjectTranslationTableEnum;
typedef enum Vehicle
{
  VEHICLE_CAR,
  VEHICLE_HOVERCRAFT,
  VEHICLE_PLANE,
  VEHICLE_FLYING_CAR,
  VEHICLE_LOOPDELOOP,
  VEHICLE_BOSSES,
  VEHICLE_TRICKY = VEHICLE_BOSSES,
  VEHICLE_BLUEY,
  VEHICLE_SMOKEY,
  VEHICLE_PTERODACTYL,
  VEHICLE_SNOWBALL,
  VEHICLE_CARPET,
  VEHICLE_BUBBLER,
  VEHICLE_WIZPIG,
  VEHICLE_ROCKET,
  VEHICLE_NO_OVERRIDE = -1,
  NUMBER_OF_VEHICLE_TYPES,
  NUMBER_OF_PLAYER_VEHICLES = 3
} Vehicle;
typedef struct Vec3s Vec3s;
typedef struct TextureInfo TextureInfo;
typedef struct Vertex Vertex;
typedef struct Triangle Triangle;
typedef struct TriangleBatchInfo TriangleBatchInfo;
typedef struct ObjectModel_44 ObjectModel_44;
typedef struct CollisionFacetPlanes
{
  u16 basePlaneIndex;
  u16 edgeBisectorPlane[3];
} CollisionFacetPlanes;
typedef struct ObjectModel
{
  TextureInfo *textures;
  Vertex *vertices;
  Triangle *triangles;
  CollisionFacetPlanes *collisionFacets;
  f32 *collisionPlanes;
  s16 *attachPoints;
  s16 numberOfAttachPoints;
  s16 unk1A;
  s16 *collisionSpheres;
  s16 collisionSpheresSize;
  s16 numberOfTextures;
  s16 numberOfVertices;
  s16 numberOfTriangles;
  s16 numberOfBatches;
  u8 pad2A[2];
  s32 fileSize;
  s16 references;
  s16 collisionFacetCount;
  u8 pad34[4];
  TriangleBatchInfo *batches;
  f32 unk3C;
  Vec3s *normals;
  ObjectModel_44 *animations;
  s16 numberOfAnimations;
  s16 numberOfAnimatedVertices;
  s32 *animatedVertexIndices;
  s16 hasAnimatedTexture;
  s16 texOffsetUpdateRate;
  u8 pad[0x2C];
} ObjectModel;
typedef struct Object Object;
typedef struct BossRaceVehicles
{
  s8 playerVehicle;
  s8 bossVehicle;
} BossRaceVehicles;
s32 func_80017A18(ObjectModel *, s32, s32 *, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *, s8 *argA, f32);
typedef struct FadeTransition
{
  u8 type;
  u8 red;
  u8 green;
  u8 blue;
  u16 duration;
  u16 endTimer;
} FadeTransition;
FadeTransition gTajChallengeTransition = {(0 & 0x3F) | ((1 << 7) & 0xC0), 0, 0, 0, 30, 15};
FadeTransition gBalloonCutsceneTransition = {(3 & 0x3F) | (0 & 0xC0), 0, 0, 0, 30, 15};
s32 D_800DC700 = 0;
s32 D_800DC704 = 0;
s16 D_800DC708 = 0;
s32 D_800DC70C = 0;
s16 D_800DC710 = 1;
s32 D_800DC714 = 0;
Object *gGhostObjStaff = 0;
s8 gRollingDemo = 0;
s32 gObjectTexAnim = 0;
s16 gTimeTrialTime = 10800;
s16 gTimeTrialVehicle = -1;
s16 gTimeTrialCharacter = 0;
u8 gHasGhostToSave = 0;
u8 gTimeTrialStaffGhost = 0;
u8 gBeatStaffGhost = 0;
s8 gLeadPlayerIndex = 0;
s8 gTwoActivePlayersInAdventure = 0;
s8 gSwapLeadPlayer = 0;
s8 gIsP2LeadPlayer = 0;
Vertex *gBoostVerts[2] = {0, 0};
Triangle *gBoostTris[2] = {0, 0};
Object *gShieldEffectObject = 0;
s32 gBoostObjOverrideID = 9;
Object *gMagnetEffectObject = 0;
f32 D_800DC768[16] = {0.0f, 1.0f, 0.70711f, 0.70711f, 1.0f, 0.0f, 0.70711f, -0.70711f, 0.0f, -1.0f, -0.70711f, -0.70711f, -1.0f, 0.0f, -0.70711f, 0.70711f};
u16 gRacerObjectTable[] = {ASSET_OBJECT_ID_KREMCAR, ASSET_OBJECT_ID_BADGERCAR, ASSET_OBJECT_ID_TORTCAR, ASSET_OBJECT_ID_CONKACAR, ASSET_OBJECT_ID_TIGERCAR, ASSET_OBJECT_ID_BANJOCAR, ASSET_OBJECT_ID_CHICKENCAR, ASSET_OBJECT_ID_MOUSECAR, ASSET_OBJECT_ID_SWCAR, ASSET_OBJECT_ID_DIDDYCAR, ASSET_OBJECT_ID_KREMLINHOVER, ASSET_OBJECT_ID_BADGERHOVER, ASSET_OBJECT_ID_TORTHOVER, ASSET_OBJECT_ID_CONKAHOVER, ASSET_OBJECT_ID_TIGERHOVER, ASSET_OBJECT_ID_BANJOHOVER, ASSET_OBJECT_ID_CHICKENHOVER, ASSET_OBJECT_ID_MOUSEHOVER, ASSET_OBJECT_ID_TICKTOCKHOVER, ASSET_OBJECT_ID_DIDDYHOVER, ASSET_OBJECT_ID_KREMPLANE, ASSET_OBJECT_ID_BADGERPLANE, ASSET_OBJECT_ID_TORTPLANE, ASSET_OBJECT_ID_CONKA, ASSET_OBJECT_ID_TIGPLANE, ASSET_OBJECT_ID_BANJOPLANE, ASSET_OBJECT_ID_CHICKENPLANE, ASSET_OBJECT_ID_MOUSEPLANE, ASSET_OBJECT_ID_TICKTOCKPLANE, ASSET_OBJECT_ID_DIDDYPLANE, ASSET_OBJECT_ID_KREMCAR, ASSET_OBJECT_ID_BADGERCAR, ASSET_OBJECT_ID_TORTCAR, ASSET_OBJECT_ID_CONKACAR, ASSET_OBJECT_ID_TIGERCAR, ASSET_OBJECT_ID_BANJOCAR, ASSET_OBJECT_ID_CHICKENCAR, ASSET_OBJECT_ID_MOUSECAR, ASSET_OBJECT_ID_SWCAR, ASSET_OBJECT_ID_DIDDYCAR, ASSET_OBJECT_ID_KREMCAR, ASSET_OBJECT_ID_BADGERCAR, ASSET_OBJECT_ID_TORTCAR, ASSET_OBJECT_ID_CONKACAR, ASSET_OBJECT_ID_TIGERCAR, ASSET_OBJECT_ID_BANJOCAR, ASSET_OBJECT_ID_CHICKENCAR, ASSET_OBJECT_ID_MOUSECAR, ASSET_OBJECT_ID_SWCAR, ASSET_OBJECT_ID_DIDDYCAR, ASSET_OBJECT_ID_TRICKYTOPS, ASSET_OBJECT_ID_WALRUS, ASSET_OBJECT_ID_DRAGONBOSS, ASSET_OBJECT_ID_TERRYBOSS, ASSET_OBJECT_ID_SNOWBALLBOSS, ASSET_OBJECT_ID_FLYINGCARPET, ASSET_OBJECT_ID_OCTOPUS, ASSET_OBJECT_ID_WIZPIG, ASSET_OBJECT_ID_WIZPIGROCKET};
BossRaceVehicles gBossVehicles[] = {{VEHICLE_CAR, VEHICLE_TRICKY}, {VEHICLE_HOVERCRAFT, VEHICLE_BLUEY}, {VEHICLE_PLANE, VEHICLE_SMOKEY}, {VEHICLE_CAR, VEHICLE_TRICKY}, {VEHICLE_HOVERCRAFT, VEHICLE_BLUEY}, {VEHICLE_HOVERCRAFT, VEHICLE_BUBBLER}, {VEHICLE_HOVERCRAFT, VEHICLE_BUBBLER}, {VEHICLE_PLANE, VEHICLE_SMOKEY}, {VEHICLE_CAR, VEHICLE_WIZPIG}, {VEHICLE_PLANE, VEHICLE_ROCKET}};
s8 D_800DC834[10] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
s8 D_800DC840[8] = {9, 1, 2, 3, 4, 5, 7, 0};
s8 gNoBoundsCheck = 0;
u32 gMagnetColours[3] = {(u32) ((((255 << 24) | (64 << 16)) | (16 << 8)) | 0), (u32) ((((16 << 24) | (64 << 16)) | (255 << 8)) | 0), (u32) ((((16 << 24) | (255 << 16)) | (64 << 8)) | 0)};
FadeTransition gRaceEndFade = {(0 & 0x3F) | (0 & 0xC0), 0, 0, 0, 40, 0xFFFF};
FadeTransition gRaceEndTransition = {(0 & 0x3F) | ((1 << 7) & 0xC0), 0, 0, 0, 40, 0};
const char sObjectOutofMemString[] = "Objects out of ram(1) !!\n";
const char sDoorNumberErrorString[] = "Door numbering error %d!!\n";
const char sObjectScopeErrorString[] = "objGetScope: Unknown scope for object %d\n";
s32 func_80017A18(ObjectModel *arg0, s32 arg1, s32 *numCollisions, f32 *originPointsX, f32 *originPointsY, f32 *originPointsZ, f32 *targetPointsX, f32 *targetPointsY, f32 *targetPointsZ, f32 *collisionRadii, s8 *surfaces, f32 scale)
{
  f32 *planes;
  s32 i;
  s32 j;
  s32 k;
  f32 sum1;
  f32 sum2;
  f32 t;
  s32 ret;
  s32 counter;
  s32 spF8;
  s32 var_s6;
  u32 redoLoop;
  f32 B1;
  f32 C1;
  f32 A;
  f32 B;
  f32 C;
  f32 y1;
  f32 x3;
  f32 *curPlanes;
  f32 new_var3;
  f32 y3;
  f32 z3;
  f32 radius;
  f32 x1;
  f32 D;
  f32 z1;
  CollisionFacetPlanes *node;
  f32 curOriginY;
  f32 curOriginX;
  f32 var_f18;
  f32 var_f20;
  f32 var_f22;
  f32 curOriginZ;
  spF8 = 0;
  planes = arg0->collisionPlanes;
  var_s6 = 1;
  for (i = 0; i < arg1; i++)
  {
    x1 = targetPointsX[i];
    y1 = targetPointsY[i];
    z1 = targetPointsZ[i];
    var_f18 = originPointsX[i];
    radius = collisionRadii[i] * scale;
    j = arg0->collisionFacetCount;
    var_f20 = ((0, originPointsY))[i];
    var_f22 = originPointsZ[i];
    counter = 0;
    var_f18 = var_f18;
    var_f20 = var_f20;
    var_f22 = var_f22;
    do
    {
      redoLoop = 0;
      for (j = 0; j < arg0->collisionFacetCount; j++)
      {
        u16 triIndex;
        node = (CollisionFacetPlanes *) (&arg0->collisionFacets[0, j]);
        triIndex = node->basePlaneIndex;
        curPlanes = planes;
        curPlanes += 4 * triIndex;
        A = curPlanes[0];
        B = curPlanes[1];
        C = curPlanes[2 & 0xFFFFu];
        D = curPlanes[3];
        sum2 = (((A * x1) + (B * y1)) + (C * z1)) + D;
        new_var3 = originPointsY[i];
        new_var3 = new_var3;
        new_var3 = (((A * originPointsX[i]) + (B * new_var3)) + (C * originPointsZ[i])) + D;
        sum1 = new_var3 - radius;
        sum2 -= radius;
        if ((sum1 >= (-0.1)) && (sum2 < (-0.1)))
        {
          if (sum1 != sum2)
          {
            t = sum1 / (sum1 - sum2);
          }
          else
          {
            sum1++;
            sum1--;
            t = 0.0f;
          }
          x3 = var_f18 + ((x1 - originPointsX[i]) * t);
          y3 = var_f20 + ((y1 - originPointsY[i]) * t);
          z3 = var_f22 + (((z1 - originPointsZ[i]) * t) * 1.0f);
          ret = 1;
          for (k = 0; (k < 3) && (ret == 1); k++)
          {
            triIndex = node->edgeBisectorPlane[k] & 0xFFFFFFFFFFFFFFFF;
            curPlanes = planes;
            curPlanes += ((triIndex * 4) & 0xFFFFFFFFFFFFFFFF) & 0xFFFFFFFFFFFFFFFF;
            sum1 = curPlanes[0];
            B1 = curPlanes[1];
            C1 = curPlanes[2];
            new_var3 = curPlanes[3];
            if (((((sum1 * x3) + (B1 * y3)) + (C1 * z3)) + new_var3) > 4.0f)
            {
              ret = 0;
            }
          }

          if (ret != 0)
          {
            redoLoop = 1;
            if (B > 0.707)
            {
              y1 = (radius - (((A * x1) + (C * z1)) + D)) / B;
            }
            else
            {
              x1 -= sum2 * A;
              y1 -= sum2 * B;
              z1 -= sum2 * C;
            }
            counter++;
            if (counter > 10)
            {
              redoLoop = 0;
              x1 = originPointsX[i];
              y1 = originPointsY[i];
              z1 = originPointsZ[i];
            }
            surfaces[i] = 0;
            targetPointsX[i] = x1;
            targetPointsY[i] = y1;
            targetPointsZ[i] = z1;
            j = arg0->collisionFacetCount;
            if (sum2)
            {
            }
          }
        }
      }

      var_f22 = curOriginZ;
      var_f20 = curOriginY;
      var_f18 = curOriginX;
    }
    while (redoLoop);
    if (counter > 0)
    {
      numCollisions[0]++;
      spF8 |= var_s6;
    }
    var_s6 <<= 1;
  }

  if (!var_f22)
  {
  }
  return spF8;
}

const char sReadOutErrorString[] = "RO error %d!!\n";
const char sPureAnguishString[] = "ARGHHHHHHHHH\n";
